name: UPDATED Scraping Movies

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Chrome from Ubuntu repo
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable || true  # fallback for potential dep errors
        google-chrome --version

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    - name: Run the scraping script
      run: python scrape.py
      
    - name: Commit and push JSON files to data-branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Create and switch to the data-branch
        git fetch
        git switch --create data-branch || git switch data-branch

        # Copy only the .json files
        git add *.json

        # Only commit if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "Update scraped JSON files - $(date)"
          git push origin data-branch
        else
          echo "No changes to commit."
        fi

