name: UPDATED Scraping Movies

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Fetch the repository code

    - name: Install Google Chrome 114
      run: |
        wget https://edgedl.me.gvt1.com/edgedl/chrome/linux/114.0.5735.90/google-chrome-stable_current_amd64.deb -O chrome114.deb
        sudo dpkg -i chrome114.deb || sudo apt-get install -f -y

    - name: Install ChromeDriver 114
      run: |
        wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraping script
      run: python scrape.py

    - name: Check for changes and commit JSON files
      run: |
        git config --global user.email "rifatahmedsajeeb@gmail.com"
        git config --global user.name "SDInHearts"
        git status

        # Add both tracked and untracked .json files in page/
        git add page/*.json

        # Check for any staged changes before committing
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update scraped movie data"
          git push
        fi
