name: UPDATED Scraping Movies

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Chrome from Ubuntu repo
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable || true  # fallback for potential dep errors
        google-chrome --version

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    - name: Run the scraping script
      run: python scrape.py

    - name: Check for changes and commit JSON files
      run: |
        git config --global user.email "rifatahmedsajeeb@gmail.com"
        git config --global user.name "SDInHearts"
        git status
        git add page/*.json
        if ! git diff --cached --quiet; then
          git commit -m "Update scraped movie data"
          git push
        else
          echo "No changes to commit"
